{
 "title": "VEGA",
 "description": "Main server",
 "tags": [
  "windows_exporter",
  "prometheus",
  "VEGA",
  "promdapter",
  "tuya_exporter",
  "solis_exporter",
  "PiKVM",
  "weather"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "3s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "60s" },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(windows_system_system_up_time, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "PiKVM Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "hwi_memory_available_mb{category=\"Physical\"} * 1048576",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "__auto",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "hwi_memory_used_mb{category=\"Physical\"} * 1048576",
     "legendFormat": "__auto"
    },
    {
     "application": { "filter": "" },
     "expr": "hwi_virtual_memory_committed_mb * 1048576",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "__auto",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "hwi_memory_available_mb{category=\"Virtual\"} * 1048576",
     "legendFormat": "__auto"
    },
    {
     "application": { "filter": "" },
     "expr": "hwi_memory_used_mb",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "__auto",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "hwi_memory_load{category=\"Physical\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Memory Clock",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hwi_memory_clock_mhz * 2", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Power Info",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tuya_smartplug_power", "legendFormat": "Power" },
    { "expr": "tuya_smartplug_current", "legendFormat": "Current" },
    { "expr": "tuya_smartplug_voltage", "legendFormat": "Voltage" }
   ]
  },
  {
   "title": "PiKVM Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory CAS Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hwi_memory_tcas_t", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PiKVM Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_thermal_zone_temp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "hwi_core_usage", "legendFormat": "CPU {{ sensor }}" }
   ]
  },
  {
   "title": "CPU Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "hwi_cpu_package_power_w", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "GHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hwi_core_clock_mhz / 1000", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Solis Inverter Info",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "power", "text": "Current Generation Power", "type": "number" }
     ],
     "source": "url",
     "type": "json",
     "url": "http://localhost:8686/",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "energy.today", "text": "Daily Generation", "type": "number" }
     ],
     "source": "url",
     "type": "json",
     "url": "http://localhost:8686/",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "energy.total", "text": "Total Generation", "type": "number" }
     ],
     "source": "url",
     "type": "json",
     "url": "http://localhost:8686/",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "PiKVM CPU Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hwi_cpu_voltage_v", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PiKVM CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(irate(node_cpu_seconds_total {cpu=\"0\",mode!=\"idle\"} [1m])) by (instance)) / sum(irate(node_cpu_seconds_total[1m])) by (instance) * 400",
     "legendFormat": "CPU 1"
    },
    {
     "expr": "(sum(irate(node_cpu_seconds_total {cpu=\"1\",mode!=\"idle\"} [1m])) by (instance)) / sum(irate(node_cpu_seconds_total[1m])) by (instance) * 400",
     "legendFormat": "CPU 2"
    },
    {
     "expr": "(sum(irate(node_cpu_seconds_total {cpu=\"2\",mode!=\"idle\"} [1m])) by (instance)) / sum(irate(node_cpu_seconds_total[1m])) by (instance) * 400",
     "legendFormat": "CPU 3"
    },
    {
     "expr": "(sum(irate(node_cpu_seconds_total {cpu=\"3\",mode!=\"idle\"} [1m])) by (instance)) / sum(irate(node_cpu_seconds_total[1m])) by (instance) * 400",
     "legendFormat": "CPU 4"
    }
   ]
  },
  {
   "title": "System Temperatures (ºC)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "hwi_cpu_tctltdie_c", "legendFormat": "{{source}}" },
    { "expr": "hwi_motherboard_c", "legendFormat": "{{source}}" },
    { "expr": "hwi_gpu_temperature_c", "legendFormat": "{{source}}" },
    { "expr": "hwi_gpu_hot_spot_temperature_c", "legendFormat": "{{label_name}}" },
    { "expr": "node_thermal_zone_temp", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Weather",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "columns": [
      { "selector": "current_weather.temperature", "text": "Temperature", "type": "number" },
      { "selector": "daily.sunrise", "text": "Sunrise", "type": "timestamp" },
      { "selector": "daily.sunset", "text": "Sunset", "type": "timestamp" },
      { "selector": "daily.uv_index_max", "text": "UV Index", "type": "number" }
     ],
     "source": "url",
     "type": "json",
     "url": "https://api.open-meteo.com/v1/forecast?latitude=-21.14&longitude=-47.99&daily=sunrise,sunset,uv_index_max,uv_index_clear_sky_max&current_weather=true&forecast_days=1&timezone=America%2FSao_Paulo",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "GPU and VRAM Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "hwi_gpu_d3d_usage", "legendFormat": "{{sensor}}" },
    {
     "expr": "hwi_gpu_d3d_memory_dedicated_mb",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "GPU and VRAM Frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    { "expr": "hwi_gpu_clock_mhz", "legendFormat": "{{sensor}}" },
    { "expr": "hwi_gpu_memory_clock_mhz", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "GPU Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "hwi_gpu_ppt_w", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "GPU Fan",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hwi_gpu_fan_rpm", "legendFormat": "__auto" },
    { "expr": "hwi_gpu_fan", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "GPU Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "V" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hwi_gpu_core_voltage_v", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Drives Remaining Life (SSD)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hwi_drive_remaining_life", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "Drives Temperatures (ºC)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "hwi_drive_temperature_c", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "Partition Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_free_bytes{volume=\"C:\"} / windows_logical_disk_size_bytes{volume=\"C:\"})*100",
     "legendFormat": "{{volume}}"
    },
    {
     "expr": "100 - (windows_logical_disk_free_bytes{volume=\"D:\"} / windows_logical_disk_size_bytes{volume=\"D:\"})*100",
     "legendFormat": "{{volume}}"
    },
    {
     "expr": "100 - (windows_logical_disk_free_bytes{volume=\"E:\"} / windows_logical_disk_size_bytes{volume=\"E:\"})*100",
     "legendFormat": "{{volume}}"
    },
    {
     "expr": "100 - (windows_logical_disk_free_bytes{volume=\"F:\"} / windows_logical_disk_size_bytes{volume=\"F:\"})*100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Wi-Fi Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hwi_network_dl_rate_kbs{source= \"Network: TP-Link Wireless USB Adapter\"} * 1024",
     "legendFormat": "Download"
    },
    {
     "expr": "hwi_network_up_rate_kbs{source= \"Network: TP-Link Wireless USB Adapter\"} * 1024",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Drives Read",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    { "expr": "hwi_drive_read_rate_mbs", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "Drives Write",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    { "expr": "hwi_drive_write_rate_mbs", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "Ethernet Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hwi_network_dl_rate_kbs{source= \"Network: RealTek Semiconductor RTL8168/8111 PCI-E Gigabit Ethernet NIC\"} * 1024",
     "legendFormat": "Download"
    },
    {
     "expr": "hwi_network_up_rate_kbs{source= \"Network: RealTek Semiconductor RTL8168/8111 PCI-E Gigabit Ethernet NIC\"} * 1024",
     "legendFormat": "Upload"
    }
   ]
  }
 ]
}